name: Firestore_Security_Rules_Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - firestore/rules/**
      - firestore/test/**
      - firestore/*.json
      - .github/workflows/firestore_security_rules_test.yaml
  push:
    branches:
      - master
    paths:
      - firestore/rules/**
      - firestore/test/**
      - firestore/*.json
      - .github/workflows/firestore_security_rules_test.yaml

jobs:
  firestore_security_rules_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: firestore
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm install
          npm i -g firebase-tools
          firebase emulators:exec --only firestore 'npm test'